LANGUAGES = {
    "ua": {
        "welcome": "=== Ласкаво просимо до Підземелля ===",
        "enter_name": "Введи ім'я героя: ",
        "choose_class": "\nОбери клас:",
        "warrior": "1. Воїн — висока сила, міцна броня",
        "archer": "2. Лучник — висока спритність, швидкий",
        "mage": "3. Маг — високий інтелект, заклинання",
        "random": "4. Випадковий клас",
        "choice": "\nВибір: ",
        "invalid": "Невірний вибір — спробуй ще раз",
        "dungeon_level": "=== Рівень підземелля: {} ===",
        "crossroads": "Перед вами розвилка:",
        "left": "1. Наліво",
        "forward": "2. Прямо",
        "right": "3. Направо",
        "direction": "\nКуди йдете? ",
        "deeper": "\nВи занурюєтесь глибше... Рівень: {}",
        "game_over": "\nГра закінчена!",
        "your_turn": "=== Твій хід ===",
        "attack": "1 Атакувати",
        "block": "2 Блокувати",
        "run": "3 Втекти",
        "battle_choice": "Оберіть дію: ",
        "hero_attack_damage": "{} завдає {} шкоди {}у HP: {}/{}",
        "enemy_attack_damage": "{} завдає {} шкоди {} HP: {}/{}",
        "block_damage": "{} блокує удар",
        "dragon_run": "Від дракона не втекти!",
        "roll": "Кидок {} проти складності {}",
        "run_success": "Втеча успішна!",
        "run_fail": "Втекти не вдалось...",
        "invalid_choice": "Невірний вибір, твій персонаж довго думає і пропускає хід",
        "battle_starts": "Бій починається! {} vs {}",
        "run_success 2": "Ти зник у темряві підземелля...",
        "battle_win": "{} переміг!",
        "battle_lose": "{} зустрів смирть...",
        "dragon_line 1": "\n Спускаючись в найтемнішу частину підземелля, ви помічаєте величезну печеру з купою золота.",
        "dragon_line 2": "Але перед нею стоїть дракон готовий захищати своє золото",
        "dragon_hp": "HP Дракона: {}/{}",
        "dragon_damage": "Дракон завдає {} шкоди → HP: {}/{}",
        "dragon_line 3": "Покритий ранами дракон готовий битись з УСІХ СИЛ, ТА ГОТОВИЙ ПОКАЗАТИ ВСЮ СВОЮ МІЦЬ",
        "dragon_dbf": "Рев дракона шкодить вашим обладкункам. Броню зменшено",
        "dragon_fire": "\nДракон готує вогняний подих",
        "make_roll": "Здійсніть рятівний кидок (напишіть \"кидок\"): ",
        "roll_bonus": "Кидок: {} + {} (бонус) = {} проти DC 15",
        "half_damage": "Ви змогли частково ухилитись, але вогонь завдає {} шкоди",
        "full_damage": "Провал! Отримуєте повну шкоду: {}",
        "invalid_roll": "Введіть \"кидок\"!",
        "dragon_defeated": f"Дракон переможений! Місто врятоване від його постійних атак, а половина вкраденого драконом золота дістається вам.",
        "game_win": "Гру пройдено!!!",
        "dragon_wins": "Ваше тіло не витримало жару вогню дракона та перетворилось на попіл. Дракон переміг",

    },
    "en": {
        "welcome": "=== Welcome to the Dungeon ===",
        "enter_name": "Enter hero name: ",
        "choose_class": "\nChoose class:",
        "warrior": "1. Warrior — high strength, heavy armor",
        "archer": "2. Archer — high agility, fast",
        "mage": "3. Mage — high intelligence, spells",
        "random": "4. Random class",
        "choice": "\nChoice: ",
        "invalid": "Invalid choice — try again",
        "dungeon_level": "=== Dungeon level: {} ===",
        "crossroads": "You see a crossroads:",
        "left": "1. Left",
        "forward": "2. Forward",
        "right": "3. Right",
        "direction": "\nWhich way? ",
        "deeper": "\nYou descend deeper... Level: {}",
        "game_over": "\nGame over!",
        "your_turn": "=== Your turn ===",
        "attack": "1 Attack",
        "block": "2 Block",
        "run": "3 Run",
        "battle_choice": "Choose action: ",
        "hero_attack_damage": "{} deals {} damage to {} HP: {}/{}",
        "enemy_attack_damage": "{} deals {} damage to {} HP: {}/{}",
        "block_damage": "{} blocks damage",
        "dragon_run": "You can not run away from a dragon",
        "roll": "Roll {} vs roll difficulty {}",
        "run_success": "You run successfully",
        "run_fail": "Your run fails",
        "invalid_choice": "Your character thinks too long and skips the turn",
        "battle_starts": "Battle starts!  {} vs {}",
        "run_success 2": "You disappeared in a darkness of the dungeon",
        "battle_win": "{} wins!",
        "battle_lose": "{} faced death...",
        "dragon_line 1": "As you descend into the darkest part of the dungeon, you notice a massive cavern with a pile of gold.",
        "dragon_line 2": "But there is a dragon, standing before it, ready to defend its gold.",
        "dragon_hp": "Dragon HP: {}/{}",
        "dragon_damage": "The dragon deals {} damage → HP: {}/{}",
        "dragon_line 3": "The dragon, covered in wounds, is ready to fight WITH ALL ITS MIGHT AND UNLEASH ITS FULL POWER",
        "dragon_dbf": "The dragon's roar damages your armor. Armor reduced.",
        "dragon_fire": "\nThe dragon is preparing a fiery breath.",
        "make_roll": "Make a saving throw (type \"roll\"): ",
        "roll_bonus": "Roll: {} + {} (bonus) = {} vs DC 15",
        "half_damage": "You managed to partially dodge, but the fire deals {} damage",
        "full_damage": "Fail! You take full damage: {}",
        "invalid_roll": "Type \"roll\"!",
        "dragon_defeated": "The dragon is defeated! The city is saved from its constant attacks, and half of the gold stolen by the dragon goes to you.",
        "game_win": "Game Win!",
        "dragon_wins": "Your body could not withstand the heat of the dragon's fire and turned to ash. The dragon won.",

    }
}

def t(key, lang="ua", *args):
    text = LANGUAGES[lang].get(key, key)
    if args:
        return text.format(*args)
    return text